💬 More responses
DevSnowflake/minichat pull request #1
Opened 2021-11-21 15:27 UTC by KartikeSingh

I added few more random responses :D

2021-11-21 20:32 UTC, DevAndromeda requested changes

2021-11-21 20:32 UTC, DevAndromeda commented on minichat/core.py
> +            "Wait, I am trying to make sense".
this should be `,` not `.`

2021-11-22 03:27 UTC, KartikeSingh commented on minichat/core.py
> +            "Wait, I am trying to make sense".
my bad, imma fix it

2021-11-22 03:33 UTC, KartikeSingh commented
closing the pr because old fork is deleted :C

2021-11-22 03:33 UTC, closed without merging