better responses 💬
DevSnowflake/minichat pull request #2
Opened 2021-11-22 03:34 UTC by KartikeSingh

- fixed the issue
- added more responses

2021-11-22 05:46 UTC, vierofernando requested changes

2021-11-22 05:46 UTC, vierofernando commented on minichat/core.py
> +            "Interesting, Indeed!",
change this to `Interesting indeed!`

2021-11-22 05:46 UTC, vierofernando commented on minichat/core.py
> +            "Kiddo go and complete your maths homeowork first"
try `go complete` instead of `go and complete`

2021-11-22 05:46 UTC, vierofernando commented on minichat/core.py
> +            "ig, You don't have a life",
the comma here is not needed

2021-11-22 05:46 UTC, vierofernando commented on minichat/core.py
> +            "Do you have sense? oh yea you don't xD",
try `you don't make any sense` for better wording.

2021-11-22 06:49 UTC, KartikeSingh commented
okay null chan

2021-11-22 10:34 UTC, vierofernando commented
thanks! <3

2021-11-22 10:40 UTC, DevAndromeda requested changes
We are not tryna roast users here, please update the responses.

2021-11-23 09:41 UTC, KartikeSingh commented
> We are not tryna roast users here, please update the responses.

okay xD

2022-10-17 03:10 UTC, KartikeSingh commented
my messages are too cringe, i feel like closing the pr, sorry for weird commits 💀

2022-10-17 03:10 UTC, closed without merging